import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
const $=id=>document.getElementById(id), canvas=$('game');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), rand=(a,b)=>a+Math.random()*(b-a), TAU=Math.PI*2;
let renderer;
try { renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}); }
catch(e){$('loading').textContent='WebGL is unavailable. Open this game in a browser with hardware acceleration enabled.';$('play').disabled=true;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9ed1db);scene.fog=new THREE.Fog(0xb0d4d8,110,290);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,650);
scene.add(new THREE.HemisphereLight(0xd9f0ff,0x777247,2.4));const sun=new THREE.DirectionalLight(0xffdb9d,3.1);sun.position.set(-65,110,45);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-95,right:95,top:95,bottom:-95,near:1,far:280});sun.shadow.bias=-.0008;sun.shadow.normalBias=.04;scene.add(sun);
const world=new THREE.Group();scene.add(world);const obstacles=[], hitMeshes=[], loot=[], bots=[], effects=[], covers=[], turbines=[];
const mats={};function mat(color){return mats[color]??=new THREE.MeshStandardMaterial({color,roughness:.86,flatShading:true});}
function mesh(geo,color,x=0,y=0,z=0,parent=world){const m=new THREE.Mesh(geo,typeof color==='number'?mat(color):color);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function box(w,h,d,c,x,y,z,p=world){return mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,p);}
function cylinder(rt,rb,h,n,c,x,y,z,p=world){return mesh(new THREE.CylinderGeometry(rt,rb,h,n),c,x,y,z,p);}
function block(x,z,w,d,h,color,y=0){const m=box(w,h,d,color,x,y+h/2,z);const o={x,z,w,d,minY:y,maxY:y+h,mesh:m,hp:Infinity};obstacles.push(o);hitMeshes.push(m);m.userData.obstacle=o;return m;}
function height(x,z){const r=Math.hypot(x,z);return Math.max(-2,1.1+Math.sin(x*.026)*1.2+Math.cos(z*.033)*1.3- Math.max(0,r-103)*.12);}
// Low-poly terrain carries per-face color; all game art is rendered geometry.
const terrainGeo=new THREE.PlaneGeometry(280,280,75,75);terrainGeo.rotateX(-Math.PI/2);const pos=terrainGeo.attributes.position;
for(let i=0;i<pos.count;i++)pos.setY(i,height(pos.getX(i),pos.getZ(i)));
const terrainFlat=terrainGeo.toNonIndexed();terrainFlat.computeVertexNormals();const colors=[];const tp=terrainFlat.attributes.position;
for(let i=0;i<tp.count;i+=3){let y=(tp.getY(i)+tp.getY(i+1)+tp.getY(i+2))/3;let c=new THREE.Color(y<.6?0xd4c18b:y<1.25?0xa0ac69:0x779e68);c.multiplyScalar(rand(.94,1.07));for(let j=0;j<3;j++)colors.push(c.r,c.g,c.b);}
terrainFlat.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const ground=mesh(terrainFlat,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:true}));ground.castShadow=false;hitMeshes.push(ground);
const water=mesh(new THREE.PlaneGeometry(1800,1800),new THREE.MeshStandardMaterial({color:0x4daeb4,roughness:.32,metalness:.25}),0,-1.6,0);water.rotation.x=-Math.PI/2;water.castShadow=false;
const sunDisk=mesh(new THREE.SphereGeometry(10,20,16),new THREE.MeshBasicMaterial({color:0xffefd0}),-180,125,-245);sunDisk.castShadow=false;
function house(x,z,w,d,c){const y=height(x,z);block(x,z,w,d,5.6,c,y);const roof=mesh(new THREE.ConeGeometry(w*.79,2.6,4),0x415d63,x,y+6.9,z);roof.rotation.y=Math.PI/4;roof.scale.z=d/w;for(const side of [-1,1]){for(const off of [-.25,.25]){box(w*.18,1.4,.08,0x274b59,x+w*off,y+3.3,z+side*(d/2+.05));box(w*.2,.1,.12,0xe3d3b1,x+w*off,y+2.58,z+side*(d/2+.1));}}box(1.5,2.8,.12,0x334a51,x,y+1.4,z+d/2+.1);box(w+1,.3,2,0xd2c092,x,y+.15,z+d/2+.7);cylinder(.25,.25,3,6,0xe1c891,x-w/2+.2,y+1.5,z+d/2+1.3);cylinder(.25,.25,3,6,0xe1c891,x+w/2-.2,y+1.5,z+d/2+1.3);box(w+1,.25,2,0x597575,x,y+3,z+d/2+.7);}
const towns=[[-28,-20],[29,28],[-56,47],[44,-52]];
for(const [x,z] of towns){house(x,z,9,8,0xd6bd91);house(x+17,z+4,7,9,0xa5b9aa);house(x+6,z-17,8,7,0xc28e72);for(let j=0;j<4;j++){const xx=x+rand(-7,15),zz=z+12+j*3;block(xx,zz,2.3,2,1.9,0x8e6d4c,height(xx,zz));}}
// Central beacon and supplies plaza.
const cy=height(0,0);cylinder(9,10,.6,8,0xb6b5a0,0,cy+.1,0);block(0,0,4,4,11,0xc1c9b9,cy);box(5.5,.5,5.5,0x315b65,0,cy+11,0);const beacon=mesh(new THREE.CylinderGeometry(.7,.7,2,8),new THREE.MeshStandardMaterial({color:0xd6f3b4,emissive:0xa7ef77,emissiveIntensity:2}),0,cy+12,0);cylinder(.15,.2,7,6,0x314f5e,0,cy+16,0);
function free(x,z,r=2){return Math.hypot(x,z)<111&&obstacles.every(o=>Math.abs(x-o.x)>o.w/2+r||Math.abs(z-o.z)>o.d/2+r);}
for(let i=0;i<100;i++){let x=rand(-113,113),z=rand(-113,113);if(!free(x,z,5)||Math.hypot(x,z)<16)continue;let y=height(x,z),s=rand(.8,1.6);if(i%4===0){const rock=mesh(new THREE.DodecahedronGeometry(s*2.2,0),0x879b90,x,y+s*.8,z);rock.scale.set(1,.7,1.2);obstacles.push({x,z,w:s*2.7,d:s*2.7,minY:y,maxY:y+s*2.1,mesh:rock,hp:Infinity});hitMeshes.push(rock);}else{const trunk=cylinder(.35*s,.55*s,4*s,6,0x705f49,x,y+2*s,z);const o={x,z,w:s*.8,d:s*.8,minY:y,maxY:y+5*s,mesh:trunk,hp:Infinity};obstacles.push(o);hitMeshes.push(trunk);for(let j=0;j<3;j++){const tree=cylinder(0,(3.4-j*.75)*s,4*s,7,[0x3b7866,0x45866b,0x579477][j],x,y+(4+j*1.65)*s,z);tree.rotation.y=i;}}}
for(const [x,z] of [[-80,-55],[65,65],[80,-15]]){const y=height(x,z);block(x,z,1.5,1.5,19,0xe0dec4,y);const rotor=new THREE.Group();rotor.position.set(x,y+19,z+.8);world.add(rotor);cylinder(.55,.55,1,10,0x536f70,x,y+19,z);for(let i=0;i<3;i++){const g=new THREE.Group();g.rotation.z=i*TAU/3;rotor.add(g);const blade=box(.8,8,.18,0xeae3c9,0,4,0,g);blade.rotation.z=-.09;}turbines.push(rotor);}
// Coastal jetty.
for(let i=0;i<8;i++){box(5,.4,3,0x9f8762,-14,1,100+i*3);for(const x of [-16, -12])cylinder(.18,.18,4,6,0x66553e,x,-.8,100+i*3);}
for(let i=0;i<13;i++){const cloud=new THREE.Group();cloud.position.set(rand(-280,280),rand(65,95),rand(-280,280));world.add(cloud);for(let j=0;j<3;j++){const c=mesh(new THREE.IcosahedronGeometry(rand(6,10),1),0xe9eadb,j*8,0,0,cloud);c.scale.set(1.4,.38,1);c.castShadow=false;}}
function makeAvatar(color){const group=new THREE.Group();world.add(group);const body=new THREE.Group();group.add(body);box(.78,.88,.44,color,0,1.25,0,body);box(.58,.65,.1,0x243c49,0,1.3,-.26,body);box(.48,.16,.08,0xe4fa8f,0,1.35,.26,body);const head=box(.5,.5,.5,0xd8c9aa,0,1.96,0,body);box(.59,.25,.57,0x253b49,0,2.13,0,body);box(.46,.17,.08,0x80dbde,0,2,.28,body);const legs=[];for(let s of [-1,1]){const leg=new THREE.Group();leg.position.set(s*.23,.89,0);body.add(leg);box(.29,.72,.3,0x2a414b,0,-.35,0,leg);box(.32,.22,.49,0x1f303c,0,-.73,.08,leg);legs.push(leg);const arm=box(.25,.67,.26,color,s*.53,1.28,.22,body);arm.rotation.x=-.65;}const gun=new THREE.Group();gun.position.set(.4,1.25,.48);body.add(gun);box(.16,.2,.68,0x233842,0,0,.23,gun);box(.08,.08,.5,0x557078,0,.03,.67,gun);box(.1,.25,.16,0x2c3336,0,-.15,.2,gun);const flash=mesh(new THREE.SphereGeometry(.16,5,4),new THREE.MeshBasicMaterial({color:0xffe59a}),0,.03,.98,gun);flash.visible=false;const shadow=mesh(new THREE.CircleGeometry(.7,16),new THREE.MeshBasicMaterial({color:0x213b30,transparent:true,opacity:.2,depthWrite:false}),0,.04,0,group);shadow.rotation.x=-Math.PI/2;shadow.castShadow=false;group.traverse(m=>{if(m.isMesh){m.userData.avatar=true;}});return {group,body,head,legs,gun,flash,phase:0};}
const player={...makeAvatar(0xdba164),x:-9,z:63,y:0,vy:0,hp:100,shield:50,alive:true,kills:0,medkits:2,materials:6};player.y=height(player.x,player.z);player.group.position.set(player.x,player.y,player.z);
const weaponDefs=[{name:'AR-7 ASSAULT RIFLE',mag:30,reserve:180,damage:25,rate:.12,reload:1.65,spread:.012,range:140,pellets:1},{name:'BREACH SHOTGUN',mag:6,reserve:36,damage:16,rate:.8,reload:2.2,spread:.065,range:35,pellets:7},{name:'SCOUT MARKSMAN',mag:8,reserve:48,damage:66,rate:.85,reload:2,spread:.002,range:190,pellets:1}];let weapons=weaponDefs.map(w=>({...w,ammo:w.mag})),slot=0,reloading=0,shootCD=0,healCD=0,healTime=0,buildCD=0;
const names=['KESTREL','ROOK','EMBER','FLINT','NOVA','MOSS','VECTOR','SABLE','ECHO','BISHOP','WREN','RIFT','ATLAS','CINDER','VALE'];
function spawnBots(){for(let i=0;i<15;i++){let x,z;do{x=rand(-88,88);z=rand(-88,88);}while(!free(x,z,3)||Math.hypot(x-player.x,z-player.z)<25);const b={...makeAvatar([0xb95c50,0x8e80af,0x739b98,0xb09c5f][i%4]),x,z,y:height(x,z),vy:0,hp:100,shield:25,alive:true,name:names[i],cooldown:rand(.3,2),think:0,target:null,dir:rand(0,TAU),stuck:0};b.group.position.set(x,b.y,z);bots.push(b);}}
function dropLoot(x,z,type){const g=new THREE.Group();g.position.set(x,height(x,z)+.5,z);world.add(g);const c=[0xf9d779,0x53dbef,0xa8f077,0xc1a0ed][type];const core=box(.72,.55,.72,c,0,.2,0,g);box(.78,.13,.78,0xf2e9c9,0,.2,0,g);const ring=mesh(new THREE.TorusGeometry(.66,.025,5,24),new THREE.MeshBasicMaterial({color:c}),0,-.35,0,g);ring.rotation.x=Math.PI/2;const beam=mesh(new THREE.CylinderGeometry(.25,.5,2.6,8,1,true),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:.11,depthWrite:false,side:THREE.DoubleSide}),0,1,0,g);beam.castShadow=false;loot.push({x,z,type,g,core,base:g.position.y,active:true});}
for(let i=0;i<44;i++){let x,z;do{x=rand(-95,95);z=rand(-95,95);}while(!free(x,z,2));dropLoot(x,z,i%4);}dropLoot(-8,54,1);dropLoot(-12,59,0);dropLoot(-5,49,3);
const stormMat=new THREE.MeshBasicMaterial({color:0x9264e4,transparent:true,opacity:.2,side:THREE.DoubleSide,depthWrite:false});const storm=mesh(new THREE.CylinderGeometry(1,1,65,100,1,true),stormMat,0,25,0);storm.castShadow=false;const zoneRing=mesh(new THREE.TorusGeometry(1,.004,5,128),new THREE.MeshBasicMaterial({color:0xc3a0ff}),0,4,0);zoneRing.rotation.x=Math.PI/2;let zoneRadius=118,elapsed=0,state='lobby',yaw=0,pitch=.16,aiming=false,firing=false,matchStarted=false,clock=0,toastUntil=0,hitUntil=0,damageUntil=0,feed=[];
let audioCtx=null,muted=false;function audio(){if(!audioCtx){const AC=window.AudioContext||window.webkitAudioContext;if(AC)audioCtx=new AC();}audioCtx?.resume();}
function tone(f,d=.09,v=.04,type='triangle',end=f){if(muted||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(end,20),audioCtx.currentTime+d);g.gain.setValueAtTime(v,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d);}
function gunSound(type=0,distant=false){tone(type===1?90:type===2?150:220,type===1?.2:.1,distant?.012:.075,'sawtooth',35);}
function notify(s,d=2.5){$('toast').textContent=s;toastUntil=clock+d;}
function log(s){feed.unshift({s,t:clock+8});feed=feed.slice(0,4);}
function animateActor(a,moving,dt){a.phase+=dt*(moving?12:2);a.legs[0].rotation.x=moving?Math.sin(a.phase)*.65:0;a.legs[1].rotation.x=-a.legs[0].rotation.x;a.body.position.y=moving?Math.abs(Math.sin(a.phase))*.05:Math.sin(a.phase)*.015;a.group.position.set(a.x,a.y,a.z);a.flash.visible=clock<(a.flashUntil||0);}
function move(a,dx,dz,dt){const step=(axis,v)=>{const next=a[axis]+v;let x=axis==='x'?next:a.x,z=axis==='z'?next:a.z;if(Math.hypot(x,z)>124)return;for(const o of obstacles){if(!o.mesh.visible||a.y>o.maxY-.05||a.y+2<o.minY)continue;if(Math.abs(x-o.x)<o.w/2+.43&&Math.abs(z-o.z)<o.d/2+.43)return;}a[axis]=next;};step('x',dx);step('z',dz);let floor=height(a.x,a.z);for(const o of obstacles){if(o.mesh.visible&&Math.abs(a.x-o.x)<o.w/2+.3&&Math.abs(a.z-o.z)<o.d/2+.3&&a.y>=o.maxY-.15)floor=Math.max(floor,o.maxY);}a.vy-=20*dt;a.y+=a.vy*dt;if(a.y<floor){a.y=floor;a.vy=0;}}
const ray=new THREE.Raycaster();function sight(a,b){const origin=new THREE.Vector3(a.x,a.y+1.5,a.z),target=new THREE.Vector3(b.x,b.y+1.3,b.z);const d=target.sub(origin);ray.set(origin,d.clone().normalize());ray.far=d.length();return !ray.intersectObjects(hitMeshes.filter(m=>m.visible),false).length;}
function removeCover(o){o.mesh.visible=false;const i=hitMeshes.indexOf(o.mesh);if(i>=0)hitMeshes.splice(i,1);}
function trace(start,end,color=0xffecac){const g=new THREE.BufferGeometry().setFromPoints([start,end]);const line=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity:.9}));world.add(line);effects.push({m:line,end:clock+.07});}
function burst(x,y,z,color){for(let i=0;i<9;i++){const m=mesh(new THREE.BoxGeometry(.12,.12,.12),new THREE.MeshBasicMaterial({color}),x,y,z);effects.push({m,end:clock+.5,v:new THREE.Vector3(rand(-3,3),rand(1,4),rand(-3,3))});}}
function hurt(target,amount,by,head=false){if(!target.alive)return;const absorbed=Math.min(target.shield,amount);target.shield-=absorbed;target.hp=Math.max(0,target.hp-(amount-absorbed));if(target===player){damageUntil=clock+.3;if(healTime>0){healTime=0;notify('Healing interrupted');}}if(by===player){hitUntil=clock+.13;tone(head?950:650,.06,.03);if(head)notify('HEADSHOT',.65);}if(target.hp<=0){target.alive=false;target.group.visible=false;burst(target.x,target.y+1,target.z,0xbff0eb);if(target===player){endMatch(false,by?.name||'the storm');return;}dropLoot(target.x,target.z,Math.floor(rand(0,4)));log(`${by===player?'YOU':by?.name||'STORM'}  ›  ${target.name}`);if(by===player){player.kills++;notify(`ELIMINATED ${target.name}`,2);tone(430,.25,.04,'triangle',850);}if(bots.every(b=>!b.alive)&&player.alive)endMatch(true);}}
function shoot(){
 if(state!=='playing'||shootCD>0||reloading>0||healTime>0)return;
 const w=weapons[slot];if(w.ammo<=0){reload();return;}w.ammo--;shootCD=w.rate;player.flashUntil=clock+.055;gunSound(slot);
 scene.updateMatrixWorld(true);camera.updateMatrixWorld();const origin=new THREE.Vector3();player.gun.getWorldPosition(origin);origin.y+=.03;
 const candidates=hitMeshes.filter(m=>m.visible);for(const b of bots)if(b.alive)b.group.traverse(m=>{if(m.isMesh&&m!==b.flash){m.userData.actor=b;candidates.push(m);}});
 for(let p=0;p<w.pellets;p++){
  const spread=w.spread*(aiming?.32:1);ray.setFromCamera(new THREE.Vector2(rand(-spread,spread),rand(-spread,spread)),camera);ray.far=w.range;
  const hits=ray.intersectObjects(candidates,false);let hit=hits[0],endpoint=hit?hit.point:ray.ray.at(w.range,new THREE.Vector3());
  const direction=endpoint.clone().sub(origin);ray.set(origin,direction.clone().normalize());ray.far=direction.length();
  const obstruction=ray.intersectObjects(hitMeshes.filter(m=>m.visible),false)[0];
  if(obstruction&&obstruction.distance<direction.length()-.08){hit=obstruction;endpoint=hit.point;}
  if(hit){const a=hit.object.userData.actor;if(a){const head=hit.point.y>a.y+1.76;const distance=origin.distanceTo(endpoint);const falloff=slot===1?Math.max(.2,1-distance/60):1;hurt(a,w.damage*falloff*(head?1.7:1),player,head);}else if(hit.object.userData.obstacle){const o=hit.object.userData.obstacle;o.hp-=w.damage;if(o.hp<=0)removeCover(o);}}
  trace(origin.clone(),endpoint);
 }
 pitch=clamp(pitch-.007,-.6,1);
}
function reload(){if(state!=='playing'||reloading||healTime)return;const w=weapons[slot];if(w.ammo===w.mag)return;if(w.reserve<=0){notify('No reserve ammo. Find golden supplies.');return;}reloading=w.reload;tone(250,.12,.02);notify('RELOADING',w.reload);}
function changeWeapon(n){if(state!=='playing'||slot===n)return;slot=n;reloading=0;healTime=0;shootCD=.2;tone(400,.06,.02);document.querySelectorAll('.slot').forEach((e,i)=>e.classList.toggle('selected',i===slot));}
function heal(){if(state!=='playing'||healTime)return;if(player.hp>=100){notify('Health is already full');return;}if(player.medkits<=0){notify('No medkits. Find green supplies.');return;}reloading=0;healTime=2.6;notify('USING MEDKIT · KEEP COVER',2.6);}
function build(){if(state!=='playing'||buildCD>0)return;if(player.materials<=0){notify('No cover left. Find violet supplies.');return;}const x=player.x-Math.sin(yaw)*4,z=player.z-Math.cos(yaw)*4;const horizontal=Math.abs(Math.cos(yaw))>Math.abs(Math.sin(yaw));const w=horizontal?4.5:.4,d=horizontal?.4:4.5;if(!free(x,z,2.5)||bots.some(b=>b.alive&&Math.hypot(b.x-x,b.z-z)<3)){notify('Cannot build here');return;}const m=block(x,z,w,d,3.1,0x658a9a,height(x,z));m.userData.obstacle.hp=160;covers.push(m.userData.obstacle);player.materials--;buildCD=.6;tone(170,.12,.05);notify('COVER DEPLOYED',1);}
function requestLock(){if(!touchDevice&&canvas.requestPointerLock){try{const p=canvas.requestPointerLock();p?.catch(()=>notify('Mouse capture unavailable. Hold and drag to look.',4));}catch{notify('Hold and drag to look.',4);}}}
function begin(){audio();if(!matchStarted){spawnBots();matchStarted=true;}state='playing';$('lobby').hidden=true;$('modal').hidden=true;$('hud').hidden=false;document.body.classList.add('playing');$('touch-controls').hidden=!touchDevice;requestLock();notify('SUNSET ISLE\nBe the last survivor.',3);}
function pauseGame(){if(state!=='playing')return;state='paused';firing=false;aiming=false;keys.clear();document.exitPointerLock?.();showModal('MATCH PAUSED','Take a breath.','RESUME MATCH');}
function showModal(eyebrow,title,button){$('modal-eyebrow').textContent=eyebrow;$('modal-title').textContent=title;$('resume').innerHTML=button+' <span>↗</span>';$('modal').hidden=false;$('instructions').hidden=false;$('result').hidden=true;}
function endMatch(won,killer){state='ended';firing=false;document.exitPointerLock?.();showModal(won?'LASTLIGHT VICTORY':'MATCH COMPLETE',won?'LAST ONE STANDING.':`YOU PLACED #${bots.filter(b=>b.alive).length+1}`,'PLAY AGAIN');$('instructions').hidden=true;$('result').hidden=false;$('result').textContent=`${won?'The island is yours.':`Eliminated by ${killer}.`} ${player.kills} eliminations · ${Math.floor(elapsed/60)}m ${Math.floor(elapsed%60)}s survived.`;tone(won?520:160,.6,.08,'triangle',won?1040:60);}
$('play').onclick=begin;$('controls').onclick=()=>showModal('FIELD MANUAL','Stay in the fight.','GOT IT');$('resume').onclick=()=>{if(state==='ended'){location.reload();return;}if(state==='paused'){begin();return;}$('modal').hidden=true;};$('pause').onclick=pauseGame;
function toggleSound(){muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';if(!muted)audio();}$('sound').onclick=toggleSound;
const keys=new Set();const touchDevice=matchMedia('(pointer:coarse)').matches;let dragLook=false;
addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();if(e.repeat)return;keys.add(e.code);if(e.code==='Escape'){if(state==='playing')pauseGame();else if(state==='paused')begin();}if(e.code==='KeyM')toggleSound();if(state!=='playing')return;if(e.code==='KeyR')reload();if(e.code==='KeyE')heal();if(e.code==='KeyQ')build();if(e.code==='Space'&&player.vy===0){player.vy=8;tone(180,.08,.015);}if(/^Digit[123]$/.test(e.code))changeWeapon(+e.code.slice(-1)-1);});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',pauseGame);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame();});
canvas.addEventListener('mousedown',e=>{if(state!=='playing')return;audio();if(e.button===0){firing=true;dragLook=true;}if(e.button===2)aiming=true;if(!document.pointerLockElement)requestLock();});addEventListener('mouseup',e=>{if(e.button===0){firing=false;dragLook=false;}if(e.button===2)aiming=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(state==='playing'&&(document.pointerLockElement===canvas||dragLook)){yaw-=e.movementX*.0025*(aiming?.55:1);pitch=clamp(pitch+e.movementY*.002,-.6,1);}});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing'&&!touchDevice)pauseGame();});document.querySelectorAll('.slot').forEach(e=>e.onclick=()=>changeWeapon(+e.dataset.slot));
let joyX=0,joyZ=0,lookTouch=null;const stick=$('stick');stick.addEventListener('pointerdown',e=>{stick.setPointerCapture(e.pointerId);stickMove(e);});function stickMove(e){if(!stick.hasPointerCapture(e.pointerId))return;const r=stick.getBoundingClientRect();joyX=clamp((e.clientX-r.left-55)/40,-1,1);joyZ=clamp((e.clientY-r.top-55)/40,-1,1);stick.firstElementChild.style.transform=`translate(${joyX*28}px,${joyZ*28}px)`;}stick.addEventListener('pointermove',stickMove);function stopStick(){joyX=joyZ=0;stick.firstElementChild.style.transform='';}stick.addEventListener('pointerup',stopStick);stick.addEventListener('pointercancel',stopStick);canvas.addEventListener('touchstart',e=>{if(state==='playing'){const t=e.changedTouches[0];lookTouch={id:t.identifier,x:t.clientX,y:t.clientY};}},{passive:true});canvas.addEventListener('touchmove',e=>{if(!lookTouch||state!=='playing')return;for(const t of e.changedTouches)if(t.identifier===lookTouch.id){yaw-=(t.clientX-lookTouch.x)*.005;pitch=clamp(pitch+(t.clientY-lookTouch.y)*.005,-.6,1);lookTouch={id:t.identifier,x:t.clientX,y:t.clientY};}},{passive:true});canvas.addEventListener('touchend',()=>lookTouch=null);$('touch-fire').addEventListener('pointerdown',e=>{e.currentTarget.setPointerCapture(e.pointerId);firing=true;});for(const event of ['pointerup','pointercancel'])$('touch-fire').addEventListener(event,()=>firing=false);$('touch-jump').onclick=()=>{if(player.vy===0)player.vy=8;};$('touch-reload').onclick=reload;$('touch-heal').onclick=heal;$('touch-build').onclick=build;
const minimap=$('map').getContext('2d');let uiClock=0;
function updateHUD(){const alive=bots.filter(b=>b.alive).length+(player.alive?1:0);$('alive').textContent=alive;$('kills').textContent=player.kills;$('health').textContent=Math.ceil(player.hp);$('shield').textContent=Math.ceil(player.shield);$('health-bar').style.width=player.hp+'%';$('shield-bar').style.width=player.shield+'%';$('materials').textContent=player.materials+' COVER';$('medkits').textContent=player.medkits;const w=weapons[slot];$('ammo').textContent=reloading>0?'··':w.ammo;$('reserve').textContent='/ '+w.reserve;$('reload-note').textContent=reloading>0?`RELOADING ${reloading.toFixed(1)}s`:healTime>0?`HEALING ${healTime.toFixed(1)}s`:w.name;const angle=((yaw*180/Math.PI)%360+360)%360,dirs=['N','NW','W','SW','S','SE','E','NE'];$('compass').textContent=`${dirs[Math.round(angle/45)%8]}  ·  ${Math.round((360-angle)%360)}°`;$('toast').style.opacity=clock<toastUntil?1:0;$('hitmarker').style.opacity=clock<hitUntil?1:0;$('damage').style.opacity=clock<damageUntil?.65:0;feed=feed.filter(f=>f.t>clock);$('feed').textContent='';for(const f of feed){const d=document.createElement('div');d.textContent=f.s;$('feed').append(d);}const outside=Math.hypot(player.x,player.z)>zoneRadius;$('zone-warning').hidden=!outside;let sec=elapsed<40?40-elapsed:Math.max(0,280-elapsed);$('storm-label').textContent=(elapsed<40?'STORM IN ':zoneRadius>8?'CLOSING · ':'FINAL ZONE · ')+`${Math.floor(sec/60)}:${String(Math.floor(sec%60)).padStart(2,'0')}`;
const c=minimap;c.clearRect(0,0,190,190);c.fillStyle='#36737b';c.fillRect(0,0,190,190);c.fillStyle='#69816a';c.beginPath();c.arc(95,95,84,0,TAU);c.fill();c.fillStyle='#b9b092';for(const [x,z] of towns){c.fillRect(95+x*.69-4,95+z*.69-4,8,7);c.fillRect(95+(x+17)*.69-3,95+(z+4)*.69-3,6,7);}c.fillStyle='#8a49c54a';c.beginPath();c.rect(0,0,190,190);c.arc(95,95,zoneRadius*.69,0,TAU,true);c.fill('evenodd');c.strokeStyle='#d6aaff';c.lineWidth=2;c.beginPath();c.arc(95,95,zoneRadius*.69,0,TAU);c.stroke();c.fillStyle='#edda95';for(const l of loot)if(l.active){c.fillRect(95+l.x*.69-1,95+l.z*.69-1,2,2);}for(const b of bots)if(b.alive&&Math.hypot(b.x-player.x,b.z-player.z)<28){c.fillStyle='#ff9c80';c.beginPath();c.arc(95+b.x*.69,95+b.z*.69,2,0,TAU);c.fill();}c.save();c.translate(95+player.x*.69,95+player.z*.69);c.rotate(-yaw);c.fillStyle='#e9ff98';c.beginPath();c.moveTo(0,-6);c.lineTo(4,4);c.lineTo(0,2);c.lineTo(-4,4);c.closePath();c.fill();c.restore();c.fillStyle='#fff';c.font='10px sans-serif';c.fillText('N',91,13);}
function updateBots(dt){const actors=[player,...bots];for(const b of bots){if(!b.alive)continue;b.cooldown-=dt;b.think-=dt;if(b.think<=0){b.think=rand(.25,.55);let best=null,dist=60;for(const a of actors){if(a===b||!a.alive)continue;const d=Math.hypot(a.x-b.x,a.z-b.z);if(d<dist&&sight(b,a)){best=a;dist=d;}}b.target=best;if(!best&&Math.random()<.15)b.dir+=rand(-1,1);}
let mx=0,mz=0;const outside=Math.hypot(b.x,b.z)>zoneRadius-7;if(outside){const d=Math.hypot(b.x,b.z);mx=-b.x/d;mz=-b.z/d;}else if(b.target?.alive){const t=b.target,dx=t.x-b.x,dz=t.z-b.z,dist=Math.hypot(dx,dz);if(dist>16){mx=dx/dist;mz=dz/dist;}else if(dist<9){mx=-dx/dist*.6;mz=-dz/dist*.6;}mx+=Math.cos(clock*.8+b.dir)*.3;mz+=Math.sin(clock*.8+b.dir)*.3;b.group.rotation.y=Math.atan2(dx,dz);if(b.cooldown<=0&&dist<57&&sight(b,t)){b.cooldown=rand(.4,.8);b.flashUntil=clock+.07;const from=new THREE.Vector3(b.x,b.y+1.45,b.z),to=new THREE.Vector3(t.x+rand(-.6,.6),t.y+1.15,t.z);trace(from,to,0xffb179);if(t===player)gunSound(0,true);const accuracy=t===player?(aiming?.63:.43):.61;if(Math.random()<accuracy)hurt(t,rand(7,12),b);if(state!=='playing')return;}}else{mx=Math.sin(b.dir)*.55;mz=Math.cos(b.dir)*.55;b.group.rotation.y=b.dir;}
const speed=outside?5:3.6,oldX=b.x,oldZ=b.z;move(b,mx*speed*dt,mz*speed*dt,dt);if(Math.hypot(b.x-oldX,b.z-oldZ)<.001&&(mx||mz)){b.stuck+=dt;if(b.stuck>.6){b.dir+=1.5;move(b,-mz*speed*dt,mx*speed*dt,dt);if(b.vy===0)b.vy=7;b.stuck=0;}}else b.stuck=0;animateActor(b,Math.abs(mx)+Math.abs(mz)>.1,dt);if(Math.hypot(b.x,b.z)>zoneRadius)hurt(b,dt*(elapsed<150?5:12),null);}}
function update(dt){elapsed+=dt;zoneRadius=elapsed<40?118:Math.max(8,118-(elapsed-40)*.46);storm.scale.set(zoneRadius,1,zoneRadius);zoneRing.scale.set(zoneRadius,zoneRadius,1);stormMat.opacity=.18+Math.sin(clock*1.5)*.03;
shootCD=Math.max(0,shootCD-dt);buildCD=Math.max(0,buildCD-dt);if(reloading>0){reloading-=dt;if(reloading<=0){reloading=0;const w=weapons[slot],n=Math.min(w.mag-w.ammo,w.reserve);w.ammo+=n;w.reserve-=n;tone(440,.1,.035);}}if(healTime>0){healTime-=dt;if(healTime<=0){healTime=0;player.medkits--;player.hp=Math.min(100,player.hp+65);notify('+65 HEALTH');tone(600,.2,.04,'sine',900);}}
let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joyX,mz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+joyZ;const len=Math.hypot(mx,mz);if(len>1){mx/=len;mz/=len;}const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')?10:6)*(aiming?.6:1)*(healTime>0?.45:1);const dx=(mx*Math.cos(yaw)+mz*Math.sin(yaw))*speed*dt,dz=(-mx*Math.sin(yaw)+mz*Math.cos(yaw))*speed*dt;move(player,dx,dz,dt);player.group.rotation.y=yaw+Math.PI;animateActor(player,len>.1,dt);updateCamera(dt);if(firing)shoot();if(state!=='playing')return;updateBots(dt);if(state!=='playing')return;
if(Math.hypot(player.x,player.z)>zoneRadius)hurt(player,dt*(elapsed<150?5:12),null);
for(const l of loot){if(!l.active)continue;l.core.rotation.y+=dt;l.g.position.y=l.base+Math.sin(clock*2+l.x)*.12;if(Math.hypot(l.x-player.x,l.z-player.z)<1.65&&Math.abs(l.g.position.y-player.y)<3){if(l.type===1&&player.shield>=100)continue;if(l.type===0){for(const w of weapons)w.reserve+=w.mag;notify('AMMO RESTOCKED');}if(l.type===1){player.shield=Math.min(100,player.shield+40);notify('+40 SHIELD');}if(l.type===2){player.medkits++;notify('+1 MEDKIT · E TO HEAL');}if(l.type===3){player.materials+=3;notify('+3 COVER · Q TO BUILD');}l.active=false;l.g.visible=false;tone(650,.17,.04,'sine',1000);}}
}
function updateCamera(dt){const distance=aiming?3.1:6.4;const target=new THREE.Vector3(player.x,player.y+1.65,player.z);const cp=Math.cos(pitch),sp=Math.sin(pitch);let desired=new THREE.Vector3(player.x+Math.sin(yaw)*distance*cp+Math.cos(yaw)*.8,target.y+sp*distance+.55,player.z+Math.cos(yaw)*distance*cp-Math.sin(yaw)*.8);const offset=desired.clone().sub(target);ray.set(target,offset.clone().normalize());ray.far=offset.length();const hits=ray.intersectObjects(hitMeshes.filter(m=>m.visible),false);if(hits.length)desired=ray.ray.at(Math.max(.55,hits[0].distance-.3),new THREE.Vector3());desired.y=Math.max(desired.y,height(desired.x,desired.z)+.65);camera.position.lerp(desired,1-Math.exp(-18*dt));const look=new THREE.Vector3(player.x-Math.sin(yaw)*40*cp,player.y+1.65-sp*40,player.z-Math.cos(yaw)*40*cp);camera.lookAt(look);camera.fov=THREE.MathUtils.lerp(camera.fov,aiming?(slot===2?37:49):65,1-Math.exp(-12*dt));camera.updateProjectionMatrix();}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;if(state==='playing'){clock+=dt;update(dt);uiClock+=dt;if(uiClock>.08){updateHUD();uiClock=0;}}else if(state==='lobby'){clock+=dt;camera.position.set(57+Math.sin(clock*.045)*12,40,91+Math.cos(clock*.045)*7);camera.lookAt(-2,7,-12);animateActor(player,false,dt);storm.scale.set(118,1,118);zoneRing.scale.set(118,118,1);for(const l of loot){l.core.rotation.y+=dt*.6;l.g.position.y=l.base+Math.sin(clock*2+l.x)*.12;}}
if(state==='lobby'||state==='playing'){for(const t of turbines)t.rotation.z+=dt*.23;for(let i=effects.length-1;i>=0;i--){const e=effects[i];if(clock>e.end){world.remove(e.m);e.m.geometry.dispose();e.m.material.dispose();effects.splice(i,1);}else if(e.v){e.v.y-=12*dt;e.m.position.addScaledVector(e.v,dt);}}}renderer.render(scene,camera);}
addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});$('loading').hidden=true;requestAnimationFrame(frame);
